import { IsString, IsNotEmpty, IsObject, IsInt, IsIn } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger'; 
import { SubCategoryType } from '@prisma/client'; // Assuming SubCategoryType is now available

const subCategoryTypes = Object.values(SubCategoryType);

/**
 * DTO used for the second step of lesson creation: saving the content for a single sub-activity.
 * This is called repeatedly until all sub-activities for the lesson are saved.
 */
export class CreateQuestionSetDto {
  @ApiProperty({
    description: 'The ID of the parent Lesson container this question set belongs to (returned from the first POST request).',
    example: 542,
  })
  @IsNotEmpty()
  @IsInt()
  lessonId: number;

  @ApiProperty({
    description: 'The specific sub-category/activity type for this content.',
    enum: subCategoryTypes,
    example: SubCategoryType.AUDIO_COMPREHENSION,
  })
  @IsNotEmpty()
  @IsString()
  @IsIn(subCategoryTypes)
  subCategoryType: SubCategoryType;

  @ApiProperty({
    description: 'The exact system prompt provided to the AI to generate this specific activity content.',
    example: 'Generate a B1 level dialogue about travel and five comprehension questions.',
  })
  @IsNotEmpty()
  @IsString()
  prompt: string;

  @ApiProperty({
    description: 'The structured JSON content generated by the AI for this activity.',
    example: {
      dialogue: "Hello, how are you?",
      questions: [{ id: 1, text: "What did he say?" }]
    },
  })
  @IsNotEmpty()
  @IsObject()
  content: object;
}