import {
  IsString,
  IsNotEmpty,
  IsObject,
  IsInt,
  IsOptional,
} from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

/**
 * DTO for saving question set content for a lesson.
 */
export class CreateQuestionSetDto {
  @ApiPropertyOptional({
    description:
      'The ID of the QuestionSet (only needed when updating existing)',
    example: 123,
  })
  @IsOptional()
  @IsInt()
  id?: number;

  @ApiProperty({
    description: 'The ID of the parent Lesson this question set belongs to.',
    example: 542,
  })
  @IsNotEmpty()
  @IsInt()
  lessonId: number;

  @ApiProperty({
    description:
      'The exact system prompt provided to the AI to generate this content.',
    example:
      'Generate a B1 level dialogue about travel with comprehension questions.',
  })
  @IsNotEmpty()
  @IsString()
  prompt: string;

  @ApiProperty({
    description: 'The structured JSON content generated by the AI.',
    example: {
      dialogue: 'Hello, how are you?',
      questions: [{ id: 1, text: 'What did he say?' }],
    },
  })
  @IsNotEmpty()
  @IsObject()
  content: object;
}
