version: '3.9'

services:
  postgres:
    image: postgres:17
    container_name: chessus_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chessus_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: softvence/cheesus-app:${APP_VERSION}
    container_name: chessus-app
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/chessus_db
      APP_VERSION: ${APP_VERSION}
      NODE_ENV: production
    ports:
      - "5001:5001"
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "
      npx prisma migrate deploy &&
      node dist/main.js
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
    name: chessus-server_db_data
