// src/module/lesson/dto/create-lesson.dto.ts

import { IsString, IsNotEmpty, IsObject, IsOptional, IsIn } from 'class-validator';
import { LessonType, Difficulty } from '@prisma/client'; 
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger'; 
const lessonTypes = Object.values(LessonType);
const difficultyLevels = Object.values(Difficulty);

export class CreateLessonDto {
  @ApiProperty({
    description: 'The type of lesson being created.',
    enum: lessonTypes,
    example: LessonType.READING,
  })
  @IsNotEmpty()
  @IsString()
  @IsIn(lessonTypes)
  type: LessonType;

  @ApiProperty({
    description: 'The proficiency level this lesson is targeted at.',
    enum: difficultyLevels,
    example: Difficulty.B1,
  })
  @IsNotEmpty()
  @IsString()
  @IsIn(difficultyLevels)
  difficulty: Difficulty;

  @ApiProperty({
    description: 'The exact system prompt provided to the AI to generate the content.',
    example: 'Generate a B1 level reading passage and five multiple-choice questions about ordering food at an Italian restaurant. The output must be JSON.',
  })
  @IsNotEmpty()
  @IsString()
  prompt: string;

  @ApiProperty({
    description: 'The structured JSON content generated by the AI (Passage, Questions, Answers, etc.).',
    // Use an example of the expected structure
    example: {
      passage: "Maria asked the waiter for un bicchiere d'acqua minerale...",
      questions: [
        { id: 1, text: "What did Maria order?", options: ["Water", "Wine"], correct: "Water" }
      ]
    },
  })
  @IsNotEmpty()
  @IsObject()
  content: object;

  @ApiPropertyOptional({
    description: 'If set to false, the lesson is saved as a draft and will not be accessible to users until published.',
    default: true,
  })
  @IsOptional()
  isPublished?: boolean;
}